baseURL = "https://ko-lab.github.io/ko-lab-website-publish/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "KO-LAB"
theme = "cupper-hugo-theme"
googleAnalytics = ""
disqusShortname = "yourdiscussshortname"
enableGitInfo = true
publishDir = "public"
assetDir = "static"
[taxonomies]
  tag = "tags"

[permalinks]
  post = "/:filename/"

[imaging]
  quality = 99

[params]
  description = "A Space to Explore, Create and Share. 🚀"
  homeMetaContent = "A Space to Explore, Create and Share"
  footer = ""
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat = "Jan 2, 2006"
  codePenUser = "someUser"
  katex = false
[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
#  [[menu.nav]]
#    name = "Blog"
#    url = "/post/"
#    weight = 2
  [[menu.nav]]
    name = "Events"
    url = "/events/"
    weight = 3
  [[menu.nav]]
    name = "The Space"
    url = "/thespace/"
    weight = 4
  [[menu.nav]]
    name = "Projects"
    url = "/projects/"
    weight = 5
  [[menu.nav]]
    name = "Membership"
    url = "/membership"
    weight = 6
  [[menu.nav]]
    name = "Links"
    url = "/links"
    weight = 7
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 8
  [[menu.nav]]
    name = "Privacy"
    url = "/privacy"
    weight = 9
