name: CI
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '30 5 * * *'
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Update theme
        # (Optional)If you have the theme added as submodule, you can pull it and use the most updated version
        run: git submodule update --init --recursive

      - name: Build
        # remove --minify tag if you do not need it
        # docs: https://gohugo.io/hugo-pipes/minification/
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            personal_token: ${{ secrets.TOKEN }}
            publish_dir: ./docs
            publish_branch: master
